AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda Auth Proxy em Python para o RepairShop

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    Runtime: python3.12
    Environment:
      Variables:
        REPAIRSHOP_APP_URL: "http://host.docker.internal:8080"

Resources:
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      CodeUri: ./
      Events:
        LoginApi:
          Type: Api
          Properties:
            Path: /auth/login
            Method: post
